version: '3.7'

services:

  postgres:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app-db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
